-- Create email_preferences table
CREATE TABLE IF NOT EXISTS email_preferences (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  email VARCHAR(255) NOT NULL,
  newsletter BOOLEAN DEFAULT TRUE,
  offers BOOLEAN DEFAULT TRUE,
  festive BOOLEAN DEFAULT TRUE,
  others BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  UNIQUE KEY unique_user (user_id),
  INDEX idx_email (email)
);
